"""Re-enrich fixture source metadata in place.

When a fixture was generated by a live pipeline run, Tavily may have left
many sources with `publisher: null` and `source_type: "unknown"`. This
script walks each fixture, fills in the publisher/source-type from the
URL hostname using `generator.utils.publisher_from_url` and
`infer_source_type`, recomputes authority/freshness/relevance scores
where appropriate, and writes the fixture back.

Idempotent. Safe to run multiple times.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from generator.schemas import calculate_source_authority_score
from generator.utils import (
    calculate_freshness_score,
    infer_source_type,
    publisher_from_url,
)


def enrich_fixture(path: Path) -> tuple[int, int]:
    """Return (sources_updated, sources_total) for the fixture at `path`."""
    payload = json.loads(path.read_text(encoding="utf-8"))
    graph = payload.get("evidence_graph") or {}
    sources = graph.get("sources", [])

    updated = 0
    for source in sources:
        url = source.get("url") or ""
        changed = False

        # Hostname-derived publisher when missing or empty.
        if not source.get("publisher"):
            inferred_publisher = publisher_from_url(url)
            if inferred_publisher:
                source["publisher"] = inferred_publisher
                changed = True

        # Hostname-derived source type when "unknown".
        if source.get("source_type") in (None, "", "unknown"):
            new_type = infer_source_type(source.get("publisher"), url).value
            if new_type != source.get("source_type"):
                source["source_type"] = new_type
                # Recalculate authority for the new type.
                source["authority_score"] = calculate_source_authority_score(
                    type("S", (), {"name": new_type, "value": new_type})()
                    if False
                    else __import__("generator.schemas", fromlist=["SourceType"]).SourceType(new_type)
                )
                changed = True

        # Refresh freshness score if published_at exists.
        published_at = source.get("published_at")
        if published_at:
            source["freshness_score"] = calculate_freshness_score(published_at)
            changed = True

        if changed:
            updated += 1

    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False, default=str))
    return updated, len(sources)


def main() -> None:
    fixture_dir = ROOT / "tests" / "fixtures"
    for fixture_path in sorted(fixture_dir.glob("*.json")):
        updated, total = enrich_fixture(fixture_path)
        print(f"{fixture_path.name}: {updated}/{total} sources enriched")


if __name__ == "__main__":
    main()
